export const PROVINCES = [
  { name: 'Beijing', cnName: '北京' },
  { name: 'Tianjin', cnName: '天津' },
  { name: 'Hebei', cnName: '河北' },
  { name: 'Shanxi', cnName: '山西' },
  { name: 'Inner Mongolia', cnName: '内蒙古' },
  { name: 'Liaoning', cnName: '辽宁' },
  { name: 'Jilin', cnName: '吉林' },
  { name: 'Heilongjiang', cnName: '黑龙江' },
  { name: 'Shanghai', cnName: '上海' },
  { name: 'Jiangsu', cnName: '江苏' },
  { name: 'Zhejiang', cnName: '浙江' },
  { name: 'Anhui', cnName: '安徽' },
  { name: 'Fujian', cnName: '福建' },
  { name: 'Jiangxi', cnName: '江西' },
  { name: 'Shandong', cnName: '山东' },
  { name: 'Henan', cnName: '河南' },
  { name: 'Hubei', cnName: '湖北' },
  { name: 'Hunan', cnName: '湖南' },
  { name: 'Guangdong', cnName: '广东' },
  { name: 'Guangxi', cnName: '广西' },
  { name: 'Hainan', cnName: '海南' },
  { name: 'Chongqing', cnName: '重庆' },
  { name: 'Sichuan', cnName: '四川' },
  { name: 'Guizhou', cnName: '贵州' },
  { name: 'Yunnan', cnName: '云南' },
  { name: 'Tibet', cnName: '西藏' },
  { name: 'Shaanxi', cnName: '陕西' },
  { name: 'Gansu', cnName: '甘肃' },
  { name: 'Qinghai', cnName: '青海' },
  { name: 'Ningxia', cnName: '宁夏' },
  { name: 'Xinjiang', cnName: '新疆' },
  { name: 'Hong Kong', cnName: '香港' },
  { name: 'Macau', cnName: '澳门' },
  { name: 'Taiwan', cnName: '台湾' },
]

export const BAD_WORDS = ['badword1', 'badword2']
